[package]
name = "elenco"
version = "0.1.0"
authors = ["DominicWrege <dominic.wrege001@stud.fh-dortmund.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features=["derive"] }
serde_json = "1.0"
actix-web = "3.3"
rss = "1.9.0"
reqwest = { version= "0.10.8", features = ["rustls-tls"], default-features = false}
askama = { version = "0.10.5", features = ["with-actix-web"] }
thiserror = "1.0.22"
bcrypt = "0.9.0"
anyhow = "1.0.34"
postgres-types =  { version = "0.1.3", features=["derive", "serde_json-1"] }
deadpool-postgres = "0.5.0"
tokio-postgres = { version = "0.5.0", features=["with-chrono-0_4", "with-serde_json-1"] }
tokio-pg-mapper = {git ="https://github.com/Dowwie/tokio-postgres-mapper.git", rev="3cc64beee8fd05f54467a9bff742c346c0fe4dd0"}
tokio-pg-mapper-derive = "0.1.4"
actix-files = "0.5.0"
rand = "0.8"
futures-util = "0.3.8"
time = "0.2.22"
email_address = "0.2.0"
url = { version = "2.2.0", features=["serde"] } 
actix-session = "0.4.0"
refinery = { version= "0.4.0", features = ["tokio-postgres"] }
env_logger = "0.8.1"
chrono = "0.4.19"
log = "0.4.11"
askama_actix = "0.11.1"
validator = {version = "0.12", features=["derive"] }
isolang = "1.0.0"
tree_magic_mini = "1.0.0"
mime = "0.3.16"
blake3 = "0.3.7"

[dependencies.tokio]
version = "0.2.23"
features = ["rt-threaded", "sync", "time", "macros", "fs"]



