[package]
name = "elenco"
version = "0.1.0"
authors = ["DominicWrege <dominic.wrege001@stud.fh-dortmund.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features=["derive"] }
serde_json = "1.0"
actix-web = "3.2.0"
rss = "1.9.0"
reqwest = "0.10.8"
askama = { version = "0.10.3" }
thiserror = "1.0.22"
bcrypt = "0.9.0"
anyhow = "1.0.34"
postgres-types =  { version = "0.1.3", features = ["derive"] }
deadpool-postgres = "0.5.0"
tokio-postgres = "0.5.0"
tokio-pg-mapper = "0.1.8"
tokio-pg-mapper-derive = "0.1.5"
actix-files = "0.4.0"
rand = "0.7.3"
use = "0.0.0"
futures-util = "0.3.8"
time = "0.2.22"
email_address = "0.2.0"
url = { version = "2.2.0", features=["serde"] } 
actix-session = "0.4.0"
refinery = { version= "0.4.0", features = ["tokio-postgres"] }
[dependencies.tokio]
version = "0.2.23"
features = ["rt-threaded", "sync", "time"]
