version: "3.1"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: hundpwd
      POSTGRES_DB: podcast
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
