version: "3.1"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: harra
      POSTGRES_PASSWORD: hund
      POSTGRES_DB: podcast
    ports:
      - 5432:5432
